### ISSUE TITLE
בדיקת המשחק

### ISSUE THREAD

**Issue by michael-lemberger** [PikaTeam/Numos#2]
המשחק יפה מאוד, אבל אני לא כל כך מצליח להבין כמה דברים. 
ניסיתי להלביש את המומיה עם הכפתורים ולא עשה כלום, וגם לא נשאלתי שאלה. האם הפונקציונאליות לא עובדת פשוט? עברתי לחדר הבא ואין שם כלום גם... 
בנוסף, סדרו את הרזולוציה של המשחק כך שיהיה אפשר להכנס למצב מסך מלא במשחק שלכם.

**Comment by LioraPinkhasov** [comment]
בוצע
